name: On Push Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore
        
      - name: Create Check Run Build
        id: create_check
        uses: actions/github-script@v4
        with:
          script: |
            const { data: checkRun } = await github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: 'Build Check',
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Build Status',
                summary: 'Build passed successfully!'
            });
            console.log(`Check Run created: ${checkRun.html_url}`);
